name: Deploy Vuepress

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/.vuepress/dist
